Controllers/BlogPostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechTalkBlog.Data;
using TechTalkBlog.Helpers;
using TechTalkBlog.Models; 
using TechTalkBlog.Services.Interfaces;
using X.PagedList;

namespace TechTalkBlog.Controllers
{
    
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BlogUser> _userManager;
        private readonly ILogger<BlogPostsController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IBlogTagService _blogTagService;
        private readonly IBlogService _blogService;
        private readonly IImageService _imageService;
        private readonly IEmailSender _emailService;


        public BlogPostsController(ApplicationDbContext context,                                   
                                    IBlogTagService blogTagService,
                                    IBlogService blogService,
                                    IImageService imageService,
                                    UserManager<BlogUser> userManager,
                                    ILogger<BlogPostsController> logger,
                                    IConfiguration configuration,
                                    IEmailSender emailService)
        {
            _context = context;
            _blogTagService = blogTagService;
            _blogService = blogService;
            _imageService = imageService;
            _userManager = userManager;
            _logger = logger;
            _configuration = configuration;
            _emailService = emailService;
        }

        #region Task<IActionResult> ContactMe()
        [Authorize]
        public async Task<IActionResult> ContactMe()
        {
            string? blogUserId = _userManager.GetUserId(User);
            if (blogUserId == null)
            {
                return NotFound();
            }
            BlogUser? blogUser = await _context.Users.FirstOrDefaultAsync(u => u.Id == blogUserId);
            return View(blogUser);
        }

        #endregion

        #region Task<IActionResult> ContactMe([Bind("FirstName, LastName, Email")] BlogUser blogUser, string? message)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ContactMe([Bind("FirstName, LastName, Email")] BlogUser blogUser, string? message)
        {
            string? swalMessage = string.Empty;
            if (ModelState.IsValid)
            {
                try
                {
                    string? adminEmail = _configuration["AdminEmail"] ?? Environment.GetEnvironmentVariable("AdminEmail");
                    await _emailService.SendEmailAsync(adminEmail!, $"Contact Me Mesage from - {blogUser.FullName}", message!);
                    swalMessage = "Email Sent Successfully";
                }
                catch (Exception)
                {

                    throw;
                }
                swalMessage = "Error: Unable to send message";
            }
            return RedirectToAction("Index", new { swalMessage });
        }

        #endregion

        #region Task<IActionResult> Index(int? categoryId, int? pageNum)
        // GET: BlogPosts
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? categoryId, int? pageNum)
        {

            IPagedList<BlogPost> blogPosts;
            // new service included
            int pageSize = 4;
            int page = pageNum ?? 1;



            if (categoryId == null)
            {
                // normal operation
                blogPosts = await (await _blogService.GetBlogPostsAsync()).ToPagedListAsync(page, pageSize);
               
            }
            else
            {
                // filtered by category
                blogPosts = await (await _blogService.FilterBlogPostByCategory(categoryId)).ToPagedListAsync(page, pageSize);
            }

            // make service call
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Tags"] = new SelectList(_context.Tags, "Id", "Name");
            return View(blogPosts);
        }

        #endregion

        #region Task<IActionResult> Archived(int? tagId)
        // GET: BlogPosts
        public async Task<IActionResult> Archived(int? tagId)
        {

            IEnumerable<BlogPost> blogPosts;
            // new service included

            blogPosts = await _blogService.GetAllArchivedBlogPostsAsync(tagId);

            // make service call
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Tags"] = new MultiSelectList(_context.Tags, "Id", "Name");
            return View(blogPosts);
        }

        #endregion

        #region Task<IActionResult> Draft(int? tagId)
        // GET: BlogPosts
        public async Task<IActionResult> Draft(int? tagId)
        {

            IEnumerable<BlogPost> blogPosts;
            // new service included

            blogPosts = await _blogService.GetAllDraftBlogPostsAsync(tagId);

            // make service call
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Tags"] = new MultiSelectList(_context.Tags, "Id", "Name");
            return View(blogPosts);
        }

        #endregion

        #region Task<IActionResult> Popular(int? pageNum)
        [AllowAnonymous]
        public async Task<IActionResult> Popular(int? pageNum)
        {
            int pageSize = 4;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> popularBlogs;
            popularBlogs = await (await _blogService.GetPopularBlogsAsync()).ToPagedListAsync(page, pageSize);

            // make service call
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Tags"] = new MultiSelectList(_context.Tags, "Id", "Name");
            return View(popularBlogs);
        }

        #endregion

        #region Task<IActionResult> Favorites(int? pageNum)
        [Authorize]
        public async Task<IActionResult> Favorites(int? pageNum)
        {
            BlogUser? user = await _userManager.GetUserAsync(User);
            int pageSize = 4;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> favoriteBlogs;
            if (user != null)
            {
                favoriteBlogs = await (await _blogService.GetFavoriteBlogPostsAsync(user!.Id)).ToPagedListAsync(page, pageSize);

                // make service call
                ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
                ViewData["Tags"] = new MultiSelectList(_context.Tags, "Id", "Name");
                return View(favoriteBlogs);
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Tags"] = new MultiSelectList(_context.Tags, "Id", "Name");
            return View();
        }

        #endregion

        #region Task<IActionResult> Details(string? slug)
        // GET: BlogPosts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string? slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            // New BlogService in Use
            var blogPost = await _blogService.GetBlogBySlugAsync(slug);

            if (blogPost == null)
            {
                return NotFound();
            }

            // Increment view count
            blogPost.ViewCount++;
            await _blogService.UpdateBlogPostAsync(blogPost);

            return View(blogPost);
        }

        #endregion

        #region Create()
        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {

            // make a service call
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["Tags"] = new SelectList(_context.Tags, "Id", "Name");
            return View();
        }

        #endregion

        #region Task<IActionResult> Create([Bind("Id,Title,Abstract,Content,IsPublished,CategoryId,Tags,ImageFile,ImageData,ImageType")] BlogPost blogPost, IEnumerable<int> selected)
        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Abstract,Content,IsPublished,CategoryId,Tags,ImageFile,ImageData,ImageType")] BlogPost blogPost, IEnumerable<int> selected)
        {
            ModelState.Remove("BlogUserId");
            ModelState.Remove("Slug");

            if (ModelState.IsValid)
            {
                string? newSlug = StringHelper.BlogPostSlug(blogPost.Title);
                if (!await _blogService.IsValidSlugAsync(newSlug, blogPost.Id))
                {
                    ModelState.AddModelError("Title", "A similar Title/Slug is already in use. Please choose a different title.");

                    // make a service call
                    ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
                    ViewData["Tags"] = new SelectList(_context.Tags, "Id", "Name", blogPost.Tags);

                    return View(blogPost);
                }

                blogPost.Slug = newSlug;
                blogPost.CreatedDate = DateTimeOffset.Now.ToUniversalTime();

                if (blogPost.ImageFile != null)
                {

Views/Shared/_AuthorAreaPartial.cshtml
@using TechTalkBlog.Services.Interfaces
@using TechTalkBlog.Enums
@inject IImageService _ImageService


<!-- Start Author Area  -->
<div class="axil-author-area axil-author-banner bg-secondary" id="authorArea">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-author">
                    <div class="media">
                        <div class="thumbnail">
                            <a href="#">
                                <img src="@_ImageService.ConvertByteArrayToFile(null, null, DefaultImage.AuthorImage)" alt="Author Images" style="height:150px;width:150px">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="author-info">
                                <h1 class="title"><a href="#">Jay McKee Jr</a></h1>
                                <span class="b3 subtitle">Full Stack .NET Web Application Developer</span>
                            </div>
                            <div class="content">
                                <p class="b1 description">With 5+ years of developing experience, I dedicate myself to continuous learning of all things .NET. Currently, I am working on earning my certification in Azure Fundamentals.</p>
                                <blockquote class="b1 description">"Whether you think you can or you think you can't, you're right!" -Anonymous</blockquote>
                                <blockquote>The more you learn, the more you'll learn; there's more to learn. -Ramsey Lewis</blockquote>
                                <ul class="social-share-transparent size-md">                               
                                    <li><a href="https://www.instagram.com/jmj_dotnetdev/" taget="_blank"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="https://github.com/McKeeJerry-FS" taget="_blank"><i class="fab fa-github"></i></a></li>
                                    <li><a href="https://www.linkedin.com/in/jjerry-mckee-jr/" taget="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                                    <li><a href="mailto:jerrymckeejr.dev@gmail.com" taget="_blank"><i class="far fa-envelope"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Author Area  -->

Views/Shared/_BlogCardPartial.cshtml
@model BlogPost
@using TechTalkBlog.Enums
@using TechTalkBlog.Services.Interfaces
@inject IImageService _ImageService

<div class="content-block post-list-view mt--30">
    <div class="post-thumbnail">
        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
            <img src="@_ImageService.ConvertByteArrayToFile(Model?.ImageData, Model?.ImageType, DefaultImage.BlogPostImage)" alt="Post Images" class="border border-2 border-secondary">
        </a>
@*         <a class="video-popup icon-color-secondary size-medium position-top-center" href="post-details.html"><span class="play-icon"></span></a>
 *@    </div>
    <div class="post-content">
        <div class="post-cat">
            <div class="post-cat-list">
                <a class="hover-flip-item-wrapper" href="#">
                    <span class="hover-flip-item">
                        <span data-text="@Model?.Category?.Name">@Model?.Category?.Name</span>
                    </span>
                </a>
            </div>
        </div>
        <h4 class="title">
            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
                @Model?.Title
            </a>
        </h4>
        <div class="post-meta-wrapper">
            <div class="post-meta">
                <div class="content">
                    <h6 class="post-author-name">
                        <a class="hover-flip-item-wrapper" href="author.html">
                            <span class="hover-flip-item">
                                <span data-text="Jay McKee Jr">Jay McKee Jr</span>
                            </span>
                        </a>
                    </h6>
                    <ul class="post-meta-list">
                        <li>@Model?.CreatedDate.ToString("MMM dd, yyyy")</li>
                        <li>@Model?.Comments?.Count()</li>
                        <li><span id="numLikes">@Model!.Likes.Where(l => l.IsLiked == true).Count() Likes</span></li>
                    </ul>
                </div>
            </div>
            <ul class=" justify-content-end">
                @foreach (Tag tag in Model!.Tags)
                {

                    <a href="#" class="badge rounded-pill border border-1 bg-primary text-light fw-normal">@tag.Name</a>
                }
            </ul>
        </div>
    </div>
</div>

Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login || Tech Pulse</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.png">

    <!-- CSS
    ============================================ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/vendor/font-awesome.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick-theme.css">
    <link rel="stylesheet" href="~/assets/css/vendor/base.css">
    <link rel="stylesheet" href="~/assets/css/plugins/plugins.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/theme.css">

</head>

<body>
    <div class="main-wrapper">
        <div id="my_switcher" class="my_switcher">
            <ul>
                <li>
                    <a href="javascript: void(0);" data-theme="light" class="setColor light">
                        <span title="Light Mode">Light</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                        <span title="Dark Mode">Dark</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Start Maintanence Area  -->
        <div class="">
            <div class="container">
                <div class="row align-items-center">
                    <div class="order-2 order-lg-1 col-lg-6 mt_md--40 mt_sm--40">
                        <div class="content">
                            @*<div class="logo">
                            <a href="index.html">
                            <img class="dark-logo" src="~/assets/images/logo/logo-black.png" alt="Logo Images">
                            <img class="light-logo" src="~/assets/images/logo/logo-white2.png" alt="Logo Images">
                            </a>
                            </div>*@
                            @RenderBody()

                        </div>
                    </div>
                    <div class="order-1 order-lg-2 col-lg-5 offset-lg-1">
                        <div class="thumbnail">
                            <img src="~/img/istockphoto-1281150061-612x612.jpg" alt="Images">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Maintanence Area  -->
        <!-- Start Back To Top  -->
        <a id="backto-top"></a>
        <!-- End Back To Top  -->
    </div>

    <!-- JS
    ============================================ -->
    <!-- Modernizer JS -->
    <script src="~/assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="~/assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="~/assets/js/vendor/bootstrap.min.js"></script>
    <script src="~/assets/js/vendor/slick.min.js"></script>
    <script src="~/assets/js/vendor/tweenmax.min.js"></script>
    <script src="~/assets/js/vendor/js.cookie.js"></script>
    <script src="~/assets/js/vendor/jquery.style.switcher.js"></script>


    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>

</html>

Views/Shared/_LogoutPartial.cshtml
<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "BlogPosts", new { area = "" })">    
</form>

Views/Shared/_SideBarPartial.cshtml
@using TechTalkBlog.Services.Interfaces
@inject IBlogService _blogService
@inject IImageService _imageService
@using TechTalkBlog.Enums



<!-- Start Sidebar Area  -->
<div class="sidebar-inner">

    <!-- Start Single Widget  -->
    <div class="axil-single-widget widget widget_categories mb--30">
        <ul>
            @foreach (Category category in (await _blogService.GetCategoriesAsync()).Take(4))
            {
                <li class="cat-item">
                    <a asp-action="Index" asp-controller="BlogPosts" asp-route-categoryId="@category.Id" class="inner">
                        <div class="thumbnail">
                            <img src="@_imageService.ConvertByteArrayToFile(category.ImageData, category.ImageType, DefaultImage.CategoryImage)" alt="">
                        </div>
                        <div class="content">
                            <h5 class="title">@category.Name</h5>
                        </div>
                    </a>
                </li>

            }
            
        </ul>
    </div>
    <!-- End Single Widget  -->
    <!-- Start Single Widget  -->
    <div class="axil-single-widget widget widget_search mb--30">
        <h5 class="widget-title">Search</h5>
        <form asp-action="SearchIndex" asp-controller="BlogPosts" method="get">
            <div class="axil-search form-group">
                <button type="submit" class="search-button"><i class="fal fa-search"></i></button>
                <input type="text" class="form-control" placeholder="Search" name="searchString" value="@ViewBag.Search"/>
            </div>
        </form>
    </div>
    <!-- End Single Widget  -->
    <!-- Start Single Widget  -->
    <div class="axil-single-widget widget widget_postlist mb-30">
        <h5 class="widget-title">Popular on Tech Pulse</h5>
        <!-- Start Post List  -->
        <div class="post-medium-block">
            @foreach (BlogPost blogPost in (await _blogService.GetPopularBlogsAsync()).Take(5))
            {
                <div class="content-block post-medium mb--20">
                    <div class="post-thumbnail">
                        <a asp-action="Details" asp-controller="BlogPosts" asp-route-id="@blogPost?.Id">
                            <img src="@_imageService.ConvertByteArrayToFile(blogPost.ImageData, blogPost.ImageType, DefaultImage.BlogPostImage)" alt="Post Images">
                        </a>
                    </div>
                    <div class="post-content">
                        <h6 class="title">
                            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost?.Slug">
                                @blogPost!.Title
                            </a>
                        </h6>
                        <div class="post-meta">
                            <ul class="post-meta-list">
                                <li>@blogPost!.CreatedDate.ToString("MMM dd, yyyy")</li>
                                <li>@blogPost!.Comments!.Count()</li>
                            </ul>
                        </div>
                    </div>
                </div>

            }
            
            

        </div>
        <!-- End Post List  -->

    </div>
    <!-- End Single Widget  -->
    <!-- Start Single Widget  -->
    <div class="axil-single-widget widget widget_social mb--30">
        <h5 class="widget-title">Stay In Touch</h5>
        <!-- Start Post List  -->
        <ul class="social-icon md-size justify-content-center">
            <li><a href="https://www.instagram.com/jay_codes_20/" taget="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://github.com/McKeeJerry-FS" taget="_blank"><i class="fab fa-github"></i></a></li>
            <li><a href="https://www.linkedin.com/in/jjerry-mckee-jr/" taget="_blank"><i class="fab fa-linkedin-in"></i></a></li>
            <li><a href="mailto:jerry.mckee.jr0882@gmail.com" taget="_blank"><i class="far fa-envelope"></i></a></li>
        </ul>
        <!-- End Post List  -->
    </div>
    <!-- End Single Widget  -->
    <!-- Start Single Widget  -->
    @* <div class="axil-single-widget widget widget_instagram mb--30">
    <h5 class="widget-title">Instagram</h5>
    <!-- Start Post List  -->
    <ul class="instagram-post-list-wrapper">
    <li class="instagram-post-list">
    <a href="#">
    <img src="assets/images/small-images/instagram-01.jpg" alt="Instagram Images">
    </a>
    </li>
    <li class="instagram-post-list">
    <a href="#">
    <img src="assets/images/small-images/instagram-02.jpg" alt="Instagram Images">
    </a>
    </li>
    <li class="instagram-post-list">
    <a href="#">
    <img src="assets/images/small-images/instagram-03.jpg" alt="Instagram Images">
    </a>
    </li>
    <li class="instagram-post-list">
    <a href="#">
    <img src="assets/images/small-images/instagram-04.jpg" alt="Instagram Images">
    </a>
    </li>
    <li class="instagram-post-list">
    <a href="#">
    <img src="assets/images/small-images/instagram-05.jpg" alt="Instagram Images">
    </a>
    </li>
    <li class="instagram-post-list">
    <a href="#">
    <img src="assets/images/small-images/instagram-06.jpg" alt="Instagram Images">
    </a>
    </li>
    </ul>
    <!-- End Post List  -->
    </div> *@
    <!-- End Single Widget  -->
</div>
<!-- End Sidebar Area  -->